{% set name = "multi-model-server" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/multi-model-server/archive/v{{ version }}.tar.gz
  sha256: 64876dbfd56671d34aedc40ec8de7988bd3ed25c3806cd463aaa62c094890ab8
  patches:
    - skip-tests.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - multi-model-server = mms.model_server:start
    - multi-model-export = mms.export_model:main
  skip: True  # [win or osx]

requirements:
  build:
    - openjdk 8.*
  host:
    - python
    - pip
  run:
    - python
    - psutil
    - pillow
    - future
    - model-archiver

test:
  requires:
    - pip
    - openjdk 8.*
  commands:
    - pip check
    - multi-model-server --help

about:
  home: https://github.com/awslabs/multi-model-server
  summary: 'Multi Model Server (MMS) is a flexible and easy to use tool for serving deep learning models trained using any ML/DL framework.'
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://github.com/awslabs/multi-model-server/blob/master/docs/README.md
  dev_url: https://github.com/awslabs/multi-model-server

extra:
  recipe-maintainers:
    - sodre
