{% set name = "multi-model-server" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/multi-model-server/archive/v{{ version }}.tar.gz
  sha256: bf026cb899158b1f057a61e6aedb2f09c35263c3c7380e5ef50e1a70b53b4ac6
  patches:
    - skip-tests.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - multi-model-server = mms.model_server:start
    - multi-model-export = mms.export_model:main

requirements:
  build:
    - openjdk 8.*
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - psutil
    - pillow
    - future
    - model-archiver

test:
  requires:
    - pip
    - openjdk 8.*
  commands:
    - pip check
    - multi-model-server --help

about:
  home: https://github.com/awslabs/multi-model-server
  summary: Multi Model Server (MMS) is a flexible and easy to use tool for serving deep learning models trained using any ML/DL framework.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://github.com/awslabs/multi-model-server/blob/master/docs/README.md
  dev_url: https://github.com/awslabs/multi-model-server

extra:
  recipe-maintainers:
    - sodre
